In [1]:
import os
import pandas as pd
import sys

print(pd.__version__)

1.5.0

In [2]:
results_file = 'preliminary_results.csv'

if not os.path.exists(results_file):
    print(f'File {results_file} not found.')
    sys.exit(-1)

df = pd.read_csv(results_file, sep='|')

In [3]:
df.mean(numeric_only=True).round(0).to_frame()

                          0
compileTime         68750.0
apiTime              1065.0
apiIncrementalDiff     81.0

In [4]:
df.median(numeric_only=True).round(0).to_frame()

                          0
compileTime         69864.0
apiTime              1042.0
apiIncrementalDiff     42.0

In [5]:
total_commits = 6839

In [6]:
df.mean(numeric_only=True).to_frame().multiply(total_commits).divide(60 * 1000).round(0)

                         0
compileTime         7836.0
apiTime              121.0
apiIncrementalDiff     9.0